modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="IGNORE_SERVER_VERSION"

[[mixins]]
config="apothic_dynamic_preview.mixins.json"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.21.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.60,22)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="apothic_attributes"
type="required"
versionRange="[2.4.0,3.0.0)"
ordering="AFTER"
side="CLIENT"
